#Aqui é declarada a versão do docker e as imagens usadas 

version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./
        dockerfile: Dockerfile
    depends_on:
        - database_mysql
    #Isso define que o php por toda a pasta raiz será copiado para o endereço após os : que provavelmente fica dentro do apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  database_mysql:
      container_name: database_mysql
      image: mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: 1919
          MYSQL_DATABASE: BLOG_DB
          MYSQL_USER: PHmore
          MYSQL_PASSWORD: 1919
      ports:
          - "9906:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8080:80'
      restart: always
      environment:
          PMA_HOST: database_mysql
      depends_on:
          - database_mysql

